[package]
name = "redox_bootloader"
version = "0.1.0"
edition = "2018"

[lib]
name = "bootloader"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
linked_list_allocator = "0.9.1"
log = "0.4.14"
redox_syscall = "0.2.10"
redoxfs = { version = "0.4.4", default-features = false }
spin = "0.9.2"
